#! /usr/bin/env python



import rospy

from nmea_msgs.msg import Sentence

import lib_navsat_driver.driver

def nmea_sentence_callback(nmea_sentence, driver):
    try:
        driver.add_sentence(nmea_sentence.sentence, frame_id=nmea_sentence.header.frame_id, timestamp=nmea_sentence.header.stamp)
    except ValueError as e:
        rospy.logwarn("Value error, likely due to missing fields in the NMEA message. Error was: %s. Please report this issue at github.com/ros-drivers/nmea_navsat_driver, including a bag file with the NMEA sentences that caused it." % e)

if __name__ == '__main__':
    rospy.init_node('huace_topic_driver')

    driver = lib_navsat_driver.driver.ROSNMEADriver()

    rospy.Subscriber("nmea_sentence", Sentence, nmea_sentence_callback,
            driver)

    rospy.spin()
