#! /usr/bin/env python


import serial

import rospy

import lib_navsat_driver.driver

if __name__ == '__main__':
    rospy.init_node('huace_serial_driver')

    serial_port = rospy.get_param('~port','/dev/ttyUSB0')
    serial_baud = rospy.get_param('~baud',4800)
    frame_id = lib_navsat_driver.driver.ROSNMEADriver.get_frame_id()

    try:
        GPS = serial.Serial(port=serial_port, baudrate=serial_baud, timeout=2)
        driver = lib_navsat_driver.driver.ROSNMEADriver()
        while not rospy.is_shutdown():
            data = GPS.readline().strip()
            try:
                driver.add_sentence(data, frame_id)
            except ValueError as e:
                rospy.logwarn("Value error, likely due to missing fields in the NMEA message. Error was: %s. Please report this issue at github.com/ros-drivers/nmea_navsat_driver, including a bag file with the NMEA sentences that caused it." % e)

    except rospy.ROSInterruptException:
        GPS.close() #Close GPS serial port
